- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers

  tasks:
    - import_role:
        name: flask
      tags: [ flask, app ]
