---
flask_app_name: demo_app

# Should be validated by the argument
#flask_version: 10
flask_user: flask
flask_home: /home/admin/
flask_repo: https://github.com/petersimeth/basic-flask-template.git
flask_scm_ref: main  
flask_app_lauch_script: /usr/local/bin/demo_app   
virtualenv_name: "venv-{{ flask_app_name }}"  
virtualenv_home: /opt/virtual_envs
virtualenv_python: /usr/bin/python3


app_yum_packages:
  - autoconf
  - automake
  - git
  - gcc
  - libtool
  - python3

pip_dependencies:
  - virtualenv

